### ISSUE TITLE
showcasing my results and asking for any tips or pointers

### ISSUE THREAD

**Issue by gt732** [huangyangyi/TeCH#39]
Hi, 

These are my results after running through all the steps. Any tips or suggestions to get a better end result? I left most settings as default but did not use a fine tuned dreambooth model but instead used a SD checkpoint trained on the person.

https://civitai.com/models/97390/v15-arnold-schwarzenegger-total-recall90s-era-hq-dreambooth-trained-checkpoint-for-quality-preservation

I was able to do all the steps minus dreambooth with a 3090 24GB

The back of the 3d avatar has no shirt. I need to play with the back view prompts a bit.

My prompt.txt

```
A muscular Arnold Person with a strong bodybuilding physique stands confidently with his arms fully extended outward, showcasing his broad chest, defined abs, large biceps, and well-developed legs. He wears a tight-fitting white tank top that highlights his upper body muscles, and short gray athletic shorts with a zipper in the center, emphasizing his muscular thighs. He is wearing black mid-calf boots and black wristbands on both wrists. The lighting enhances the glossy appearance of his skin, emphasizing the definition of his muscles. He stands against a clean, light backdrop, which accentuates his physique and gives the image a classic, retro aesthetic|man
```

tech_geometry settings

```
  back_normal_img: /root/TeCH/exp/examples/arnold/normal/arnold_normal_back.png
  can_pose_folder: None
  da_pose_mesh: None
  front_normal_img: /root/TeCH/exp/examples/arnold/normal/arnold_normal_front.png
  img: /root/TeCH/exp/examples/arnold/png/arnold_crop.png
  keypoints_path: /root/TeCH/exp/examples/arnold/obj/arnold_smpl.npy
  last_model: /root/TeCH/exp/examples/arnold/obj/arnold_smpl.obj
  last_ref_model: None
  load_apose_mesh: False
  load_back_normal: True
  load_da_pose_mesh: False
  load_front_normal: True
  load_input_image: True
  load_keypoints: True
  load_occ_mask: False
  load_result_mesh: False
  loss_mask: None
  occ_mask: None
  smpl_model: None
exp_root: /root/TeCH/exp/examples/arnold
fp16: False
guidance:
  controlnet: None
  controlnet_conditioning_scale: 0.0
  controlnet_guidance_geometry: None
  controlnet_openpose_guidance: None
  guidance_scale: 100.0
  head_hf_key: None
  hf_key: None
  lora: None
  negative: unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, shadow, worst quality, jpeg artifacts, poorly drawn, dehydrated, noisy, poorly drawn, bad proportions, bad anatomy, bad lighting, bad composition, bad framing, fused fingers, noisy, many people, duplicate characters
  negative_normal: unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, shadow, worst quality, jpeg artifacts, poorly drawn, dehydrated, noisy, poorly drawn, bad proportions, bad anatomy, bad lighting, bad composition, bad framing, fused fingers, noisy, many people, duplicate characters
  negative_textureless: unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, shadow, worst quality, jpeg artifacts, poorly drawn, dehydrated, noisy, poorly drawn, bad proportions, bad anatomy, bad lighting, bad composition, bad framing, fused fingers, noisy, many people, duplicate characters
  normal_text: a smooth and detailed sculpture of
  normal_text_extra: 
  sd_version: 1.5
  step_range: [0.02, 0.25]
  text: A muscular Arnold Person with a strong bodybuilding physique stands confidently with his arms fully extended outward, showcasing his broad chest, defined abs, large biceps, and well-developed legs. He wears a tight-fitting white tank top that highlights his upper body muscles, and short gray athletic shorts with a zipper in the center, emphasizing his muscular thighs. He is wearing black mid-calf boots and black wristbands on both wrists. The lighting enhances the glossy appearance of his skin, emphasizing the definition of his muscles. He stands against a clean, light backdrop, which accentuates his physique and gives the image a classic, retro aesthetic
  text_extra: 
  text_geo: None
  text_head: None
  textureless_text: None
  textureless_text_extra: 
  type: stable-diffusion
  use_dreambooth: False
  use_view_prompt: True
model:
  albedo_res: 2048
  color_hash_max_res: 2048
  color_hash_num_levels: 16
  color_hidden_dim: 32
  color_num_layers: 1
  different_bg: False
  dmtet_network: hash
  geo_hash_max_res: 1024
  geo_hash_num_levels: 16
  mesh_scale: 1.0
  min_near: 0.01
  render_ssaa: 4
  single_bg_color: False
  tet_grid_scale: 0.0
  tet_grid_volume: 5e-08
  tet_num_subdiv: 1
  tet_offset_scale: 0.0
  tet_shell_decimate: 0.9
  tet_shell_offset: 0.1
  use_can_pose_space: False
  use_color_network: False
  use_dmtet_network: True
  use_explicit_tet: False
  use_texture_2d: False
  use_vertex_tex: False
profile: False
stage: geometry
sub_name: arnold
test:
  H: 800
  W: 800
  not_test_video: False
  save_mesh: True
  save_uv: False
  test: False
  write_image: False
train:
  albedo_sample_ratio: 1.0
  angle_front: 60
  angle_overhead: 30
  can_pose_sample_ratio: 0.0
  ckpt: latest
  color_chamfer_space: rgb
  color_chamfer_step: 0
  crop_for_lpips: False
  decay_lnorm_cosine_cycle: 5000
  decay_lnorm_cosine_max_iter: 10000
  decay_lnorm_iter: None
  decay_lnorm_ratio: None
  dmtet_lr: 0.1
  eval_interval: 10
  face_height_range: [0.0, 0.0]
  face_phi_diff: 30
  face_phi_range: [-90, 90]
  face_radius_range: [0.3, 0.4]
  face_sample_ratio: 0.3
  face_theta_range: [90, 90]
  fovy_range: [40, 70]
  fp16: False
  h: 512
  height_range: [-0.4, 0.4]
  init_empty_tex: False
  init_mesh: True
  init_mesh_padding: 0.0
  init_texture_3d: False
  iters: 10000
  jitter_pose: False
  lambda_color_chamfer: 0.0
  lambda_lap: 10000.0
  lambda_normal: 10000.0
  lambda_recon: 0.0
  lambda_sil: 10000.0
  lock_geo: False
  loss_mask_erosion: 0.01
  lr: 0.001
  min_lr: 0
  normal_sample_ratio: 1.0
  optim: adan
  phi_diff: 30
  phi_range: [0.0, 360.0]
  pretrained: None
  radius_range: [0.7, 1.3]
  render_relative_normal: True
  render_ssaa: 4
  single_directional_color_chamfer: False
  tet_subdiv_steps: [5000]
  textureless_sample_ratio: 0.0
  theta_range: [60, 120]
  train_both: False
  use_lap_loss: True
  w: 512
  warm_iters: 0
  workspace: None
use_gl: False
workspace: /root/TeCH/exp/examples/arnold/geometry
```

tech_texture stage

```
data:
  back_normal_img: /root/TeCH/exp/examples/arnold/normal/arnold_normal_back.png
  can_pose_folder: /root/TeCH/exp/examples/arnold/obj/arnold_apose.obj
  da_pose_mesh: None
  front_normal_img: /root/TeCH/exp/examples/arnold/normal/arnold_normal_front.png
  img: /root/TeCH/exp/examples/arnold/png/arnold_crop.png
  keypoints_path: /root/TeCH/exp/examples/arnold/obj/arnold_smpl.npy
  last_model: /root/TeCH/exp/examples/arnold/obj/arnold_pose.obj
  last_ref_model: /root/TeCH/exp/examples/arnold/obj/arnold_smpl.obj
  load_apose_mesh: True
  load_back_normal: True
  load_da_pose_mesh: False
  load_front_normal: True
  load_input_image: True
  load_keypoints: True
  load_occ_mask: True
  load_result_mesh: True
  loss_mask: None
  occ_mask: /root/TeCH/exp/examples/arnold/png/arnold_occ_mask.png
  smpl_model: None
exp_root: /root/TeCH/exp/examples/arnold
fp16: False
guidance:
  controlnet: None
  controlnet_conditioning_scale: 0.0
  controlnet_guidance_geometry: None
  controlnet_openpose_guidance: None
  guidance_scale: 100.0
  head_hf_key: None
  hf_key: None
  lora: None
  negative: unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, shadow, worst quality, jpeg artifacts, poorly drawn, dehydrated, noisy, poorly drawn, bad proportions, bad anatomy, bad lighting, bad composition, bad framing, fused fingers, noisy, many people, duplicate characters
  negative_normal: unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, shadow, worst quality, jpeg artifacts, poorly drawn, dehydrated, noisy, poorly drawn, bad proportions, bad anatomy, bad lighting, bad composition, bad framing, fused fingers, noisy, many people, duplicate characters
  negative_textureless: unrealistic, blurry, low quality, out of focus, ugly, low contrast, dull, dark, low-resolution, gloomy, shadow, worst quality, jpeg artifacts, poorly drawn, dehydrated, noisy, poorly drawn, bad proportions, bad anatomy, bad lighting, bad composition, bad framing, fused fingers, noisy, many people, duplicate characters
  normal_text: None
  normal_text_extra: 
  sd_version: 1.5
  step_range: [0.02, 0.25]
  text: A muscular Arnold Person with a strong bodybuilding physique stands confidently with his arms fully extended outward, showcasing his broad chest, defined abs, large biceps, and well-developed legs. He wears a tight-fitting white tank top that highlights his upper body muscles, and short gray athletic shorts with a zipper in the center, emphasizing his muscular thighs. He is wearing black mid-calf boots and black wristbands on both wrists. The lighting enhances the glossy appearance of his skin, emphasizing the definition of his muscles. He stands against a clean, light backdrop, which accentuates his physique and gives the image a classic, retro aesthetic
  text_extra: 
  text_geo: None
  text_head: None
  textureless_text: None
  textureless_text_extra: 
  type: stable-diffusion
  use_dreambooth: False
  use_view_prompt: True
model:
  albedo_res: 2048
  color_hash_max_res: 2048
  color_hash_num_levels: 16
  color_hidden_dim: 32
  color_num_layers: 1
  different_bg: False
  dmtet_network: hash
  geo_hash_max_res: 1024
  geo_hash_num_levels: 16
  mesh_scale: 1.0
  min_near: 0.01
  render_ssaa: 4
  single_bg_color: False
  tet_grid_scale: 0.0
  tet_grid_volume: 5e-08
  tet_num_subdiv: 1
  tet_offset_scale: 0.0
  tet_shell_decimate: 0.9
  tet_shell_offset: 0.1
  use_can_pose_space: True
  use_color_network: True
  use_dmtet_network: False
  use_explicit_tet: False
  use_texture_2d: False
  use_vertex_tex: False
profile: False
stage: texture
sub_name: arnold
test:
  H: 800
  W: 800
  not_test_video: False
  save_mesh: True
  save_uv: False
  test: False
  write_image: False
train:
  albedo_sample_ratio: 1.0
  angle_front: 60
  angle_overhead: 30
  can_pose_sample_ratio: 0.0
  ckpt: latest
  color_chamfer_space: rgb
  color_chamfer_step: 5000
  crop_for_lpips: True
  decay_lnorm_cosine_cycle: None
  decay_lnorm_cosine_max_iter: None
  decay_lnorm_iter: None
  decay_lnorm_ratio: None
  dmtet_lr: 0.1
  eval_interval: 10
  face_height_range: [0.0, 0.0]
  face_phi_diff: 30
  face_phi_range: [-90, 90]
  face_radius_range: [0.3, 0.4]
  face_sample_ratio: 0.3
  face_theta_range: [90, 90]
  fovy_range: [40, 70]
  fp16: False
  h: 512
  height_range: [-0.4, 0.4]
  init_empty_tex: False
  init_mesh: True
  init_mesh_padding: 0.0
  init_texture_3d: False
  iters: 7000
  jitter_pose: False
  lambda_color_chamfer: 1000000.0
  lambda_lap: 0.0
  lambda_normal: 0.0
  lambda_recon: 10000.0
  lambda_sil: 0.0
  lock_geo: True
  loss_mask_erosion: 0.01
  lr: 0.001
  min_lr: 0
  normal_sample_ratio: 0.0
  optim: adan
  phi_diff: 30
  phi_range: [0.0, 360.0]
  pretrained: None
  radius_range: [0.7, 1.3]
  render_relative_normal: True
  render_ssaa: 4
  single_directional_color_chamfer: False
  tet_subdiv_steps: None
  textureless_sample_ratio: 0.0
  theta_range: [60, 120]
  train_both: False
  use_lap_loss: False
  w: 512
  warm_iters: 0
  workspace: None
use_gl: False
workspace: /root/TeCH/exp/examples/arnold/texture
```

INPUT IMAGE

![arnold](https://github.com/user-attachments/assets/ac7abea5-62b9-4af9-9f33-0293b595e696)

RESULTS

https://github.com/user-attachments/assets/079c9e9b-3ed0-40c4-9a5d-3cd924cb4e7a

https://github.com/user-attachments/assets/5e10a685-9631-4059-a13f-abfbabd05515
